import { PropPanel } from "@pdfme/common";
import { HEX_COLOR_PATTERN } from "../../constants";
import { RadioGroup } from "./types";

/**
 * Property panel configuration for RadioGroup plugin
 * Defines the form fields and validation rules for radio button configuration
 */
export const propPanel: PropPanel<RadioGroup> = {
  /**
   * Schema definition for the property panel form
   * Creates input fields for configuring radio button properties
   */
  schema: ({ i18n }) => ({
    color: {
      title: i18n("schemas.color"),
      type: "string",
      widget: "color",
      props: {
        disabledAlpha: true, // Disable alpha/transparency controls
      },
      required: true,
      rules: [
        { 
          pattern: HEX_COLOR_PATTERN, 
          message: i18n("validation.hexColor") 
        },
      ],
    },
    group: {
      title: i18n("schemas.radioGroup.groupName"),
      type: "string",
      description: "Radio buttons with the same group name will be mutually exclusive"
    },
  }),

  /**
   * Default schema values for new RadioGroup instances
   * These values are used when creating a new radio button element
   */
  defaultSchema: {
    name: "", // Will be auto-generated by the system
    type: "radioGroup",
    content: "false", // Default to unselected state
    position: { x: 0, y: 0 },
    width: 8, // Default size in mm
    height: 8, // Default size in mm  
    group: "MyGroup", // Default group name
    color: "#000000", // Default black color
  },
};